# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ztime < Formula
  desc "ZuluTime developer CLI — book hours from the terminal"
  homepage "https://zulutime.io/docs/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zulutime-io/cli/releases/download/v0.1.0/ztime_0.1.0_darwin_amd64.tar.gz"
      sha256 "c2e9301a3a053cc25c43d89bb9daca3087e05cfc340f90bce4312f4c0ab384d6"

      define_method(:install) do
        bin.install "ztime"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zulutime-io/cli/releases/download/v0.1.0/ztime_0.1.0_darwin_arm64.tar.gz"
      sha256 "8e77c8dabb3e82f192610eb9b12558897281a4e19f012e6795913b99d0c1f7b9"

      define_method(:install) do
        bin.install "ztime"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulutime-io/cli/releases/download/v0.1.0/ztime_0.1.0_linux_amd64.tar.gz"
      sha256 "1d185dd6dcf29691a704cad0c76815349413887dcb9429b954c1c98e4905ae97"
      define_method(:install) do
        bin.install "ztime"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zulutime-io/cli/releases/download/v0.1.0/ztime_0.1.0_linux_arm64.tar.gz"
      sha256 "2dee1df6eb97397deab7fbc049ad1f132fab446b23225adfce737ccbf3afb637"
      define_method(:install) do
        bin.install "ztime"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ztime version")
  end
end
